// Generated by https://quicktype.io

export interface BerryResponse {
    count:    number;
    next:     string;
    previous: null;
    results:  Berry[];
}

export interface Berry {
    name: string;
    url:  string;
}
